### ISSUE TITLE
2015 MacBook Pro 15"

### ISSUE THREAD

**Issue by dcbirdwell** [jwktje/mideo#4]
Hi

This is more a FYI than an issue bc this is an older laptop so I'm not really surprised - just wanted to let you know...

I can't get Mideo to work on an old 2015 MBP
https://support.apple.com/kb/sp719?locale=en_US

- It doesn't track colours
- Can't adjust grid size
- Can't choose Output name (doesn't drop down or there are no options)

Hope this helps and thanks for such an AMAZING program!!!!
DavidB

**Comment by jwktje** [comment]
Hey! 

Weirdly I wrote this software on a 2015 MBP haha. It works fine here so there must be another reason for what you are experiencing.

1. Can you open the software without getting error prompts? 

2. Not having Outputs to choose from could be because there is no virtual midi port setup. Did you do that first?

**Comment by dcbirdwell** [comment]
Hi Jan

Ooops - that's funny. It must be "human error" on my side.

1) there are no error messages. It starts up fine

2) Oops - that's it!! I forgot that I've setup multiple Midi ports for
other projects on my iMac but not MBP.

Thank you so much for the help!
I really love Mideo - it fits nicely with my love of the interaction
between video and audio. Every time I see movement on TV now, I think "what
instrument would sound good with that"

Thanks
DavidB



PS - because we always like to know, I heard about your project in a Andrew
Huang YouTube video - D




davidb@yourplanb.com

YourPlanB.com
Web Design with a twist of Lime
